### ISSUE TITLE
WARN: "Browserslist: caniuse-lite is outdated. Please run the following command: `npm update`"

### ISSUE THREAD

**Issue by dumprop** [YunoHost-Apps/codimd_ynh#67]
### Describe the bug

some strange warnings 

### Context

- Hardware: *VPS bought online*
- YunoHost version: 4.2.8.3 

### Steps to reproduce

install codimd

### Expected behavior
installed codimd without these warnings 

### Logs

```
Installing codimd...
Validating installation parameters...
Storing installation settings...
Finding an available port...
Installing dependencies...
Configuring system user...
Creating a PostgreSQL database...
Setting up source files...
Configuring NGINX web server...
Building CodiMD... (this will take some time and resources!)
Error verifying phantomjs, continuing { Error: Command failed: /usr/bin/phantomjs --version
qt.qpa.screen: QXcbConnection: Could not connect to display
Could not connect to any X display.
at ChildProcess.exithandler (child_process.js:299:12)
at ChildProcess.emit (events.js:193:13)
at maybeClose (internal/child_process.js:999:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
killed: false,
code: 1,
signal: null,
cmd: '/usr/bin/phantomjs --version' }
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
Browserslist: caniuse-lite is outdated. Please run the following command: `npm update`
Browserslist: caniuse-lite is outdated. Please run the following command: `npm update`
Browserslist: caniuse-lite is outdated. Please run the following command: `npm update`
Browserslist: caniuse-lite is outdated. Please run the following command: `npm update`
Browserslist: caniuse-lite is outdated. Please run the following command: `npm update`
Browserslist: caniuse-lite is outdated. Please run the following command: `npm update`
Modifying a config file...
Configuring a systemd service...
Integrating service in YunoHost...
Starting a systemd service...
The service codimd has correctly executed the action start.
Configuring permissions...
Reloading NGINX web server...
Installation of CodiMD completed
Installation completed
```

*If applicable and useful, add screenshots to help explain your problem.*
![image](https://user-images.githubusercontent.com/34004367/136851394-416aea1a-6a4e-4f5e-a997-751bb66cc0f2.png)

**Comment by Konsilion** [comment]
Hey, did you find a way to solve it ?

**Comment by dumprop** [comment]
> Hey, did you find a way to solve it ?

No, but all seems working

**Comment by Konsilion** [comment]
Not for me, i have the same issue ...

**Comment by ericgaspar** [comment]
@Konsilion
> Not for me, i have the same issue ...

If you can't install CodiMD you may want to try HedgeDoc as an alternative... https://github.com/YunoHost-Apps/hedgedoc_ynh

**Comment by Konsilion** [comment]
I have a problem with HedgeDoc, the iframes do not work... So I wanted to try CodiMD :p
Maybe you can help me (but I think it's broken ...) I did : 

My version of HedgeDoc is: 1.9.2~ynh1

What I expected to happen: I have a main domain and a subdomain. I want to write my pads on the subdomain and embed them on my main domain with an iframe.

What actually happened:

Where there is the iframe my browser says http://pad.mywebsite.fr/ does not allow connection.”

I’ve already tried:

```
{
    "production": {
        "protocolUseSSL": true,
        "domain": "pad.MyWebSite.fr",
        "port": "3000",
        "urlPath": "acceuil",
        "loglevel": "info",
        "useCDN": false,
        "allowGravatar": false,
        "allowFreeURL": false,
        "allowAnonymousEdits": true,
        "defaultPermission": "locked",
        "email": true,
        "allowEmailRegister": true,
        "imageUploadType": "filesystem",
        "tooBusyLag": 1000,
        "cookiePolicy": "none",
        "hsts": {
            "enable": true,
            "maxAgeSeconds": 31536000,
            "includeSubdomains": true,
            "preload": true
        },
        "csp": {
            "enable": true,
            "directives": {
            },
            "upgradeInsecureRequests": "auto",
            "addDefaults": true,
            "addDisqus": true,
            "addGoogleAnalytics": false,
            "allowFraming": true
        },
```

I hope to find an answer one day ^^

**Comment by ericgaspar** [comment]
closing with #89
