### ISSUE TITLE
Install fails on Bullseye because of a super weird python2 syntax ? wut ?

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/codimd_ynh#69]
c.f. https://ci-apps-bullseye.yunohost.org/ci/job/365

```
39439 INFO [##########+++++++...] > Building CodiMD... (this will take some time and resources!)
78905 WARNING gyp ERR! configure error
78905 WARNING gyp ERR! stack Error: Command failed: /usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
78906 WARNING gyp ERR! stack   File "<string>", line 1
78907 WARNING gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
78907 WARNING gyp ERR! stack                       ^
78908 WARNING gyp ERR! stack SyntaxError: invalid syntax
78908 WARNING gyp ERR! stack
78956 WARNING gyp ERR! stack     at ChildProcess.exithandler (child_process.js:299:12)
78957 WARNING gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
78957 WARNING gyp ERR! stack     at maybeClose (internal/child_process.js:999:16)
78958 WARNING gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
78958 WARNING gyp ERR! System Linux 5.10.28-scaleway
78959 WARNING gyp ERR! command "/opt/node_n/n/versions/node/11.15.0/bin/node" "/opt/node_n/n/versions/node/11.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
78959 WARNING gyp ERR! cwd /var/www/codimd/node_modules/dtrace-provider
78960 WARNING gyp ERR! node -v v11.15.0
78960 WARNING gyp ERR! node-gyp -v v3.8.0
78960 WARNING gyp ERR! not ok
```

Calling `/usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3]` doesn't work, because `print` without brackets `()` is python 2 syntax ... But I don't know why npm/node/gyp would try to call python ...

Maybe moving to a newer version of npm/node/gyp would fix the issue ?

**Comment by yalh76** [comment]
seems fixed now
